In [34]:
import warnings
warnings.filterwarnings("ignore")
import nltk

In [35]:
!pip install nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

Requirement already satisfied: nltk in /opt/miniconda3/lib/python3.13/site-packages (3.9.4)
Requirement already satisfied: click in /opt/miniconda3/lib/python3.13/site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /opt/miniconda3/lib/python3.13/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /opt/miniconda3/lib/python3.13/site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in /opt/miniconda3/lib/python3.13/site-packages (from nltk) (4.67.1)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

True

In [37]:
import nltk
import pandas as pd
import numpy as np
import csv

In [38]:
df = pd.read_csv('Tweets.csv')

In [39]:
df.head()

,author,content,country,date_time,id,language,latitude,longitude,number_of_likes,number_of_shares
0,katyperry,Is history repeating itself...?#DONTNORMALIZEH...,NaN,12/01/2017 19:52,8.196330e+17,en,NaN,NaN,7900,3472
1,katyperry,@barackobama Thank you for your incredible gra...,NaN,11/01/2017 08:38,8.191010e+17,en,NaN,NaN,3689,1380
2,katyperry,Life goals. https://t.co/XIn1qKMKQl,NaN,11/01/2017 02:52,8.190140e+17,en,NaN,NaN,10341,2387
3,katyperry,Me right now 🙏🏻 https://t.co/gW55C1wrwd,NaN,11/01/2017 02:44,8.190120e+17,en,NaN,NaN,10774,2458
4,katyperry,SISTERS ARE DOIN' IT FOR THEMSELVES! 🙌🏻💪🏻❤️ ht...,NaN,10/01/2017 05:22,8.186890e+17,en,NaN,NaN,17620,4655

In [40]:
#Column ['text'] contains the tweets
print(np.random.choice(df['content'], 5)) #5 random tweets

['@najwakaram Congratulations, Najwa!'
 "@Serenadingrande ☕️ so soon &amp; tomorrow's is even better"
 'A pair of ghosts appear to play a friendly game #WHPsupernatural https://t.co/qBBUFiQxt2'
 '@omaardlc Yes! Let’s take this all the way to the end...'
 "Let's surprise them w/ followers while they're in rehearsals. Go give them some love &amp; follow @ArinRaySings @BeatriceMiller @CarlyRoseMusic"]

In [ ]:
#Types of tokenization: a) by word b) by sentence

In [41]:
#Word Tokenization in a naive way
df.loc[:5,'content'].str.split(' ')

0    [Is, history, repeating, itself...?#DONTNORMAL...
1    [@barackobama, Thank, you, for, your, incredib...
2              [Life, goals., https://t.co/XIn1qKMKQl]
3        [Me, right, now, 🙏🏻, https://t.co/gW55C1wrwd]
4    [SISTERS, ARE, DOIN', IT, FOR, THEMSELVES!, 🙌🏻...
5    [happy, 96th, gma, #fourmoreyears!, 🎈, @, LACM...
Name: content, dtype: object

In [42]:
df.loc[:5,'content'].str.lower().str.split(' ')# Next, we will remove special characters like @,

0    [is, history, repeating, itself...?#dontnormal...
1    [@barackobama, thank, you, for, your, incredib...
2              [life, goals., https://t.co/xin1qkmkql]
3        [me, right, now, 🙏🏻, https://t.co/gw55c1wrwd]
4    [sisters, are, doin', it, for, themselves!, 🙌🏻...
5    [happy, 96th, gma, #fourmoreyears!, 🎈, @, lacm...
Name: content, dtype: object

In [43]:
df.loc[:5,'content'].str.replace('@','').str.lower().str.split(' ')

#How many issues will you resolve this way? There are quotes(single & double),
#other special characters like exclamation marks, hashtags, etc.
#Note that the last word is having a '.' at the end.
#There are so many trivial issues that need to be handled

0    [is, history, repeating, itself...?#dontnormal...
1    [barackobama, thank, you, for, your, incredibl...
2              [life, goals., https://t.co/xin1qkmkql]
3        [me, right, now, 🙏🏻, https://t.co/gw55c1wrwd]
4    [sisters, are, doin', it, for, themselves!, 🙌🏻...
5    [happy, 96th, gma, #fourmoreyears!, 🎈, , lacma...
Name: content, dtype: object

In [44]:
# NLTK provides a fuction word_tokenize which can take care of most of such issues.
for each in df.loc[:5,'content'].str.lower():
    print(nltk.word_tokenize(each))

['is', 'history', 'repeating', 'itself', '...', '?', '#', 'dontnormalizehate', 'https', ':', '//t.co/ngg11quhmk']
['@', 'barackobama', 'thank', 'you', 'for', 'your', 'incredible', 'grace', 'in', 'leadership', 'and', 'for', 'being', 'an', 'exceptional…', 'https', ':', '//t.co/zuqlzpt6df']
['life', 'goals', '.', 'https', ':', '//t.co/xin1qkmkql']
['me', 'right', 'now', '🙏🏻', 'https', ':', '//t.co/gw55c1wrwd']
['sisters', 'are', 'doin', "'", 'it', 'for', 'themselves', '!', '🙌🏻💪🏻❤️', 'https', ':', '//t.co/0shuuyubev']
['happy', '96th', 'gma', '#', 'fourmoreyears', '!', '🎈', '@', 'lacma', 'los', 'angeles', 'county', 'museum', 'of', 'art', 'https', ':', '//t.co/m9n7x8xdma']

# Removing Stopwords
> Stopwords are words that you want to ignore, so you filter them out of your text when you’re processing it.
> Very common words like 'in', 'is', and 'an' are often used as stop words since they don’t add a lot of meaning to a text in and of themselves.

In [48]:
#Next step is to remove the stopwords (words that don't carry a semantic importance)
#Let's fetch the English language stopwords
from nltk.corpus import stopwords
sw_list = set(stopwords.words('english'))
print(sw_list)
#It can be seen that there are no special characters/symbols in the list of stopwords
#Let's extend it

{'isn', 'until', "isn't", "she'd", "should've", 'ma', 'that', 'while', "we're", 'all', 'more', 'do', 'shouldn', "you're", 'again', 'ain', 'yourselves', 'being', 'hers', "doesn't", 'his', "you'll", 'mustn', 'nor', 'when', 'you', 'has', "i've", 'shan', 'off', 'some', "wouldn't", 'against', 'out', "didn't", "mustn't", 'will', 'your', 'over', 'were', 'yours', "they've", 'didn', 'here', 'because', "hasn't", 'below', 'same', 'who', "it'll", 'yourself', "shan't", "i'm", "hadn't", 'myself', 'doesn', 'it', 'what', 'whom', 'd', 'which', "he'll", 'themselves', "needn't", 'wasn', 'have', 'for', 'at', 'should', "that'll", 'where', 'he', 'only', "i'd", "wasn't", 'hasn', 'is', "shouldn't", 'too', 'been', 'just', 'down', "aren't", "don't", 'each', 'a', 'most', 'couldn', 'those', 'm', 'then', 'him', 'the', 'as', 'above', 'ours', 'had', 'how', 'does', 'there', 'mightn', 'about', 'such', 'these', 'by', 'herself', 'be', 'did', 'other', 'an', "won't", 'wouldn', "it's", "it'd", "we've", "she's", 'very', 'ourselves', 'she', "she'll", "they're", 'needn', 'theirs', 'if', 'don', 'but', 'was', 'between', 'during', 'why', 'y', 'are', 't', "couldn't", 'their', 'am', 'own', 'both', 're', 'and', "he'd", 'on', 'so', 'aren', "mightn't", 'before', 'up', 'in', 'with', "they'll", 'any', 'once', 'itself', 'or', 'i', 'her', 'from', 'our', 'them', 'further', 'hadn', 've', 'can', "you've", 'this', 'o', 'himself', 'through', 'doing', "weren't", 'few', 'of', 'we', 's', 'now', "he's", 'll', 'than', "you'd", 'weren', 'my', 'to', "haven't", 'no', "we'd", 'haven', 'not', 'its', "we'll", 'won', 'after', "i'll", 'me', 'having', 'into', 'they', 'under', "they'd"}

In [49]:
sw_list.update(['@',"'",'.','"','/','!',',',"'ve","...","n't",'$',"'s"])
print(sw_list)

{'isn', 'until', "isn't", "she'd", "should've", 'ma', 'that', 'while', "we're", 'all', 'more', 'do', 'shouldn', "you're", 'again', 'ain', 'yourselves', 'being', 'hers', "doesn't", 'his', "you'll", 'mustn', 'nor', 'when', 'you', 'has', "i've", 'shan', 'off', 'some', "wouldn't", 'against', 'out', "didn't", "mustn't", 'will', 'your', 'over', 'were', 'yours', "they've", 'didn', 'here', 'because', "hasn't", 'below', 'same', 'who', "it'll", 'yourself', "shan't", "i'm", "hadn't", 'myself', 'doesn', 'it', "'s", 'what', 'whom', 'd', 'which', "n't", "he'll", 'themselves', "needn't", 'wasn', 'have', 'for', 'at', 'should', "that'll", 'where', 'he', 'only', "i'd", "wasn't", 'hasn', 'is', "shouldn't", 'too', 'been', 'just', 'down', "aren't", "don't", 'each', 'a', 'most', '"', 'couldn', 'those', 'm', 'then', 'him', '...', 'the', 'as', 'above', 'ours', 'had', 'how', 'does', 'there', 'mightn', 'about', 'such', 'these', 'by', 'herself', '!', 'be', 'did', 'other', 'an', "won't", 'wouldn', '.', "it's", "it'd", "we've", "she's", 'very', 'ourselves', 'she', "she'll", "they're", 'needn', 'theirs', 'if', 'don', 'but', 'was', "'ve", 'between', 'during', 'why', 'y', 'are', 't', "couldn't", 'their', 'am', 'own', 'both', 're', 'and', "he'd", 'on', 'so', ',', 'aren', "mightn't", 'before', 'up', 'in', 'with', "they'll", 'any', 'once', 'itself', 'or', 'i', 'her', 'from', 'our', 'them', 'further', 'hadn', 've', 'can', "you've", 'this', "'", 'o', 'himself', 'through', 'doing', "weren't", 'few', 'of', 'we', 's', 'now', "he's", 'll', 'than', "you'd", '/', '$', 'weren', 'my', 'to', "haven't", 'no', "we'd", 'haven', 'not', '@', 'its', "we'll", 'won', 'after', "i'll", 'me', 'having', 'into', 'they', 'under', "they'd"}

In [50]:
tokenized_data = []
for each in df.loc[:2, 'content'].str.lower():
    tokenized_data.append(nltk.word_tokenize(each))
print(tokenized_data)

[['is', 'history', 'repeating', 'itself', '...', '?', '#', 'dontnormalizehate', 'https', ':', '//t.co/ngg11quhmk'], ['@', 'barackobama', 'thank', 'you', 'for', 'your', 'incredible', 'grace', 'in', 'leadership', 'and', 'for', 'being', 'an', 'exceptional…', 'https', ':', '//t.co/zuqlzpt6df'], ['life', 'goals', '.', 'https', ':', '//t.co/xin1qkmkql']]

In [51]:
data = []
for line in tokenized_data:
    processed_line = []
    for word in line:
        if word not in sw_list:
            processed_line.append(word)
    data.append(processed_line)
print(data)
#We are left with only semantically meanigful words
#Depending on the output, more stopwords can be added to the sw_list above

[['history', 'repeating', '?', '#', 'dontnormalizehate', 'https', ':', '//t.co/ngg11quhmk'], ['barackobama', 'thank', 'incredible', 'grace', 'leadership', 'exceptional…', 'https', ':', '//t.co/zuqlzpt6df'], ['life', 'goals', 'https', ':', '//t.co/xin1qkmkql']]



```
# This is formatted as code
```

# Sentence Tokenization

In [52]:
#For some tasks, you might need to tokenize the data into sentences
#Sentence tokenization in a naive way
df.loc[5, 'content'].lower().split('.')

['happy 96th gma #fourmoreyears! 🎈 @ lacma los angeles county museum of art https://t',
 'co/m9n7x8xdma']

In [54]:
#ALternative: Using sentence tokenizer from NLTK
nltk.sent_tokenize(df.loc[5,'content'].lower())

['happy 96th gma #fourmoreyears!',
 '🎈 @ lacma los angeles county museum of art https://t.co/m9n7x8xdma']

# Stemming
Reduce words to their root, which is the core part of a word. Take note that the core part ('root') may not be a complete English word.

For example, the words “helping” and “helped” share the root “help.”

> There are two stemmers available in NLTK, PorterStemmer() and SnowballStemmer(). The Snowball stemmer, which is also called Porter2, is an improvement on the original Porter stemmer.

In [55]:
from nltk.stem import PorterStemmer
p_stemmer = PorterStemmer()

print(p_stemmer.stem('help'))
print(p_stemmer.stem('helped'))
print(p_stemmer.stem('helping'))

help
help
help

In [56]:
from nltk.stem import SnowballStemmer
s_stemmer = SnowballStemmer('english')

print(s_stemmer.stem('help'))
print(s_stemmer.stem('helped'))
print(s_stemmer.stem('helping'))

help
help
help

In [57]:
#Let's apply stemming on a subset of data and see the differences in the two stemmers
strings_for_stemming = df.loc[:100, 'content'].str.lower()
strings_for_stemming

0      is history repeating itself...?#dontnormalizeh...
1      @barackobama thank you for your incredible gra...
2                    life goals. https://t.co/xin1qkmkql
3                me right now 🙏🏻 https://t.co/gw55c1wrwd
4      sisters are doin' it for themselves! 🙌🏻💪🏻❤️ ht...
                             ...
96                     @sella_sandra my birthdays soon💅🏼
97                    @kpcatt @hillaryclinton next level
98                                @perrysoldier welcs ho
99             @lillysgomez @lucycowell14 not for long👋🏼
100    @perrysoldier make fun of me now, thank me lat...
Name: content, Length: 101, dtype: str

In [59]:
from nltk import word_tokenize

words_in_each_string = []
for each_string in strings_for_stemming:
    words_in_each_string.append(word_tokenize(each_string))
words_in_each_string

[['is',
  'history',
  'repeating',
  'itself',
  '...',
  '?',
  '#',
  'dontnormalizehate',
  'https',
  ':',
  '//t.co/ngg11quhmk'],
 ['@',
  'barackobama',
  'thank',
  'you',
  'for',
  'your',
  'incredible',
  'grace',
  'in',
  'leadership',
  'and',
  'for',
  'being',
  'an',
  'exceptional…',
  'https',
  ':',
  '//t.co/zuqlzpt6df'],
 ['life', 'goals', '.', 'https', ':', '//t.co/xin1qkmkql'],
 ['me', 'right', 'now', '🙏🏻', 'https', ':', '//t.co/gw55c1wrwd'],
 ['sisters',
  'are',
  'doin',
  "'",
  'it',
  'for',
  'themselves',
  '!',
  '🙌🏻💪🏻❤️',
  'https',
  ':',
  '//t.co/0shuuyubev'],
 ['happy',
  '96th',
  'gma',
  '#',
  'fourmoreyears',
  '!',
  '🎈',
  '@',
  'lacma',
  'los',
  'angeles',
  'county',
  'museum',
  'of',
  'art',
  'https',
  ':',
  '//t.co/m9n7x8xdma'],
 ['kyoto',
  ',',
  'japan',
  '1',
  '.',
  '5',
  '.',
  '17.',
  'https',
  ':',
  '//t.co/o28m0vw9lr'],
 ['🇯🇵', '@', 'sanrio', 'puroland', 'https', ':', '//t.co/exvev5umbx'],
 ['2017', 'resolution', ':', 'to', 'embody', 'authenticity', '!'],
 ['sisters', '.', 'https', ':', '//t.co/5ze21x2ank'],
 ['happy',
  'holidays',
  '!',
  'sending',
  'love',
  'and',
  'light',
  'to',
  'every',
  'corner',
  'of',
  'the',
  'earth',
  '🎁'],
 ['damn',
  ',',
  'it',
  "'s",
  'hard',
  'to',
  'wrap',
  'presents',
  'when',
  'you',
  "'re",
  'drunk',
  '.',
  'cc',
  '@',
  'santa'],
 ['when',
  'my',
  'whole',
  'fam',
  'tryna',
  'have',
  'a',
  'peaceful',
  'holiday',
  '💁🏻hehehe',
  'https',
  ':',
  '//t.co/feyq3hzdlz'],
 ['when',
  'your',
  'holiday',
  'shopping',
  'is',
  'woke',
  'af',
  '❗️blklivesmatter',
  'https',
  ':',
  '//t.co/srzzj7vhyc',
  'https',
  ':',
  '//t.co/kwvyi8yi8l'],
 ['@', 'shannonwoodward', 'have', 'you', 'been', 'hacked'],
 ['this',
  'week',
  'santa',
  'and',
  'i',
  'got',
  'to',
  'spread',
  'some',
  'cheer',
  'and',
  'have',
  'a',
  'carol',
  'sing-a-long',
  'with',
  'some',
  'beautiful…',
  'https',
  ':',
  '//t.co/vl1bij4scz'],
 ['love',
  'the',
  'music',
  'therapy',
  'program',
  'at',
  'chla',
  '!',
  'https',
  ':',
  '//t.co/xptzrf3xxa'],
 ['for', 'real', 'tho', 'https', ':', '//t.co/jxmv9q6wcs'],
 ['i',
  'ca',
  "n't",
  'wait',
  'to',
  'recreate',
  'this',
  'on',
  'a',
  'tour',
  'we',
  'do',
  'together',
  'in',
  'the',
  'next',
  '10',
  'years',
  'pls',
  'thnx',
  'https',
  ':',
  '//t.co/pqz0ncunv6'],
 ['i',
  'wan',
  'na',
  'adopt',
  'him',
  'ilhsm',
  'https',
  ':',
  '//t.co/5sr9whniey'],
 ['@',
  'jessesaintjohn',
  'imma',
  'make',
  'a',
  'best',
  'of',
  '16',
  "'",
  'spotify',
  'playlist',
  'and',
  'half',
  'of',
  'these',
  'are',
  'on',
  'there',
  '.',
  'i',
  'love',
  'our',
  'taste',
  '.'],
 ['@', 'jessesaintjohn', '@', 'kanyewest', 'fade', 'doe'],
 ['omg', 'deep', 'cut', ',', 'agreed', 'https', ':', '//t.co/0yglkuo3bj'],
 ['same', 'https', ':', '//t.co/98vbup7bzi'],
 ['fully', 'https', ':', '//t.co/iii4a58tpn'],
 ['proof',
  'that',
  'your',
  'voice',
  'actually',
  'matters',
  '!',
  '🙏🏼🙌🏼💪🏼😭',
  'https',
  ':',
  '//t.co/tawl0a9y9e'],
 ['this',
  'holiday',
  'season',
  'be',
  'the',
  'girl',
  'that',
  'takes',
  'jump',
  'photos',
  'at',
  'the',
  'mall',
  '☑️',
  'wears',
  'activewear',
  'at',
  'night…',
  'https',
  ':',
  '//t.co/0egynkf5fk'],
 ['slowly',
  ',',
  'i',
  'am',
  'coming',
  'down',
  'from',
  'the',
  'beautiful',
  'cloud',
  'that',
  'was',
  'tuesday',
  'night',
  "'s",
  'unicef',
  'snowflake…',
  'https',
  ':',
  '//t.co/bia5wug56i'],
 ['i',
  'dare',
  'you',
  'to',
  'find',
  'a',
  'better',
  'live',
  'vocal',
  'performance',
  'than',
  'this',
  'timeless',
  'masterpiece',
  ':',
  'https',
  ':',
  '//t.co/j1gw29kc7j',
  '#',
  'jenniferholliday'],
 ['this',
  '#',
  'thanksgiving',
  '#',
  'istandwithstandingrock',
  'text',
  'water',
  'to',
  '82623',
  'to',
  'help',
  'now',
  '!',
  'sign',
  'the',
  'petition',
  'here',
  ':',
  'https',
  ':',
  '//t.co/gfhqkfsb0i'],
 ['on',
  '#',
  'thanksgiving',
  ',',
  'a',
  'day',
  'with',
  'complex',
  'origins',
  ',',
  'i',
  'want',
  'to',
  'speak',
  'up',
  'in',
  'support',
  'of',
  'the',
  'standing',
  'rock…',
  'https',
  ':',
  '//t.co/ckyb7h3lcd'],
 ['heading',
  'into',
  'my',
  'family',
  '🦃-day',
  ',',
  'i',
  "'m",
  'mindful',
  'about',
  'building',
  'a',
  'bridge',
  'thru',
  'peaceful',
  'convo',
  '.',
  'try',
  'this',
  'guide',
  'from',
  '@',
  'nytimes',
  ':',
  'https',
  ':',
  '//t.co/mzbbnw1zhd'],
 ['great', 'tweet', '🏆', 'https', ':', '//t.co/z6qeywsbpt'],
 ['.',
  '@',
  'realdonaldtrump',
  'how',
  'bout',
  'you',
  'start',
  'with',
  'an',
  'apology',
  'for',
  'your',
  'divisive',
  ',',
  'racist',
  ',',
  'xenophobic',
  'rhetoric',
  '?',
  '#',
  'thanksgivingdayclapback'],
 ['caught', 'a', 'big', 'one', 'this', 'week', '🎣', '...'],
 ['let', 'it', 'be', 'known', '!', 'https', ':', '//t.co/axmajmnmgc'],
 ['back',
  'to',
  'work',
  'because',
  ':',
  'all',
  'of',
  'the',
  'above',
  '💪🏼',
  'https',
  ':',
  '//t.co/duvh7jn8oi'],
 ['operate', 'in', 'the', 'light', '.'],
 ['confused',
  '?',
  'overwhelmed',
  '?',
  'here',
  "'s",
  'the',
  'brief',
  'you',
  'need',
  'to',
  'get',
  'the',
  'gist',
  ':',
  'https',
  ':',
  '//t.co/4dwggerwmt'],
 ['at', 'midnight', 'we', 'manifest', '✨🌚✨'],
 ['yes',
  'la',
  'keep',
  'leading',
  'the',
  'way',
  '❤️',
  'https',
  ':',
  '//t.co/4lcjvcdj4u'],
 ['it',
  "'s",
  'time',
  'to',
  'turn',
  'words',
  'into',
  'action❗️there',
  'are',
  'so',
  'many',
  'steps',
  'to',
  'take',
  ',',
  'but',
  'my',
  'first',
  'vow',
  'is',
  'to…',
  'https',
  ':',
  '//t.co/1dwetgxbed'],
 ['thank',
  'you',
  'to',
  'the',
  'men',
  'and',
  'women',
  'protecting',
  'freedom',
  ',',
  'liberty',
  ',',
  'and',
  'equality',
  'for',
  'all',
  '.',
  '🙏🏼🇺🇸',
  'https',
  ':',
  '//t.co/0lcb7vydrx'],
 ['from',
  'pastor',
  'john',
  'pavlovitz',
  '``',
  'this',
  'is',
  'not',
  'about',
  'losing',
  'an',
  'election',
  "''",
  'https',
  ':',
  '//t.co/vvxyzvkyyi'],
 ['lets',
  'also',
  'work',
  'on',
  'the',
  'hearts',
  'and',
  'minds',
  'of',
  'this',
  'country',
  'and',
  'that',
  'is',
  'how',
  'real',
  'change',
  'will',
  'begin',
  '.'],
 ['remember',
  'to',
  'take',
  'care',
  'of',
  'your',
  'mental',
  'health',
  '.',
  'talk',
  'with',
  'counselors/therapists/ur',
  'tribe',
  '.',
  'lean',
  'on',
  'your',
  'friends',
  ',',
  'do',
  "n't",
  'stop',
  'communicating',
  '.'],
 ['we',
  'need',
  'more',
  'courageous',
  'men',
  'like',
  'this',
  'to',
  'speak',
  'up',
  'and',
  'say',
  'that',
  'there',
  'is',
  'great',
  'examples',
  'of',
  'men',
  'out',
  'there',
  ':',
  'https',
  ':',
  '//t.co/daruhfyssm'],
 ['🙏🏼🇺🇸peacefully', 'protest🇺🇸🙏🏼'],
 ['fight', 'for', 'what', 'is', 'right', '.'],
 ['do',
  'not',
  'sit',
  'still',
  '.',
  'do',
  'not',
  'weep',
  '.',
  'move',
  '.',
  'we',
  'are',
  'not',
  'a',
  'nation',
  'that',
  'will',
  'let',
  'hate',
  'lead',
  'us',
  '.'],
 ['we', 'will', 'never', 'be', 'silenced', '.', '#', 'lovetrumpshate'],
 ['power', 'to', 'the', 'people'],
 ['rise', 'up'],
 ['the', 'revolution', 'is', 'coming', '.'],
 ['we',
  'will',
  'never',
  'be',
  'silenced',
  '.',
  'https',
  ':',
  '//t.co/co4cybxg8j'],
 ['gon',
  'na',
  'cry',
  'my',
  'false',
  'eye',
  'lashes',
  'off',
  'tonight',
  '.',
  '❤️🙏🏼🇺🇸'],
 ['throw',
  'back',
  'to',
  'oct',
  '25th',
  'when',
  'i',
  'gave',
  'myself',
  'the',
  'best',
  'bday',
  'prezzy',
  'ever',
  'by',
  'voting',
  'for',
  'my',
  'girl…',
  'https',
  ':',
  '//t.co/i68tg6ixi1'],
 ['hope',
  'you',
  'are',
  'roaring',
  'your',
  'way',
  'to',
  'the',
  'polls',
  'still',
  '!',
  '👊🏼🦁🐯❤️🇺🇸',
  ':',
  'https',
  ':',
  '//t.co/tnqit6zia6'],
 ['✔️ote',
  '#',
  'yeson64',
  '!',
  'let',
  "'s",
  'rewrite',
  'our',
  'narrative',
  'california❗️',
  'https',
  ':',
  '//t.co/mys49evfef',
  'by',
  '@',
  'dreamhampton'],
 ['🔮', 'https', ':', '//t.co/afzxsirfhn'],
 ['if',
  'hell',
  'had',
  'a',
  'smell',
  'it',
  'would',
  'be',
  'used',
  'dental',
  'floss',
  'and',
  'earring',
  'backs',
  '.',
  '😷'],
 ['my',
  'name',
  'is',
  '🐶',
  'nugget',
  '🐶',
  'and',
  'i',
  'approve',
  'this',
  'message',
  '.',
  'go',
  '✔ote❗find',
  'out',
  'where',
  ':',
  'https',
  ':',
  '//t.co/rl2nzq97cd',
  'https',
  ':',
  '//t.co/qgouyddqac'],
 ['want',
  'niche',
  '?',
  'inside',
  'jokes',
  '?',
  'mega',
  'meta',
  '?',
  'think',
  'ur',
  'the',
  'only',
  '1',
  'thinking',
  'the',
  'demented',
  'way',
  'ur',
  'thinking',
  '?',
  'go',
  'see',
  '``',
  'oh',
  'hello',
  "''",
  'on',
  'broadway',
  '&',
  'amp',
  ';',
  'find',
  'ur',
  'ppl',
  '.'],
 ['hill-adelphia',
  'ftw',
  '!',
  'in',
  'less',
  'than',
  '3',
  'days',
  'be',
  'apart',
  'of',
  'history',
  'and',
  'make',
  '#',
  'herstory',
  '🇺🇸',
  '#',
  'november8th…',
  'https',
  ':',
  '//t.co/pnv46unbxj'],
 ['omg',
  'idk',
  'this',
  'is',
  'totes',
  'my',
  'vocab',
  'https',
  ':',
  '//t.co/weyhipxb4q'],
 ['done',
  'with',
  'my',
  '🎄christmas🎄shopping',
  '✔️',
  'https',
  ':',
  '//t.co/ww8n4sirxx'],
 ['🎣🐟🐠🐋'],
 ['aye',
  '!',
  '📲',
  'text',
  'roar',
  'to',
  '47246',
  'to',
  'score',
  'free',
  '🎟',
  'to',
  'see',
  'me',
  '&',
  'amp',
  ';',
  '@',
  'hillaryclinton',
  'this',
  'saturday',
  'in',
  'philly',
  '!',
  '(',
  'i',
  "'ll",
  'be',
  'the',
  'one',
  'singing',
  '🎤',
  ')',
  '#',
  'lovetrumpshate❤️'],
 ['welp',
  '.',
  'the',
  'airline',
  'lost',
  'my',
  'luggage',
  'so',
  'i',
  'guess',
  'i',
  "'ll",
  'just',
  'wear',
  'my',
  'tracksuit',
  'for',
  'halloween',
  '💁🏻',
  'now',
  'that',
  "'s",
  'scary',
  '.',
  '🎃'],
 ['🎃my',
  'fam',
  '&',
  'gt',
  ';',
  'your',
  'fam🎃',
  'i',
  'have',
  'roots',
  'from',
  'both',
  'santa',
  'barbara',
  'and',
  'arkansas',
  '(',
  'think',
  'appalachian…',
  'https',
  ':',
  '//t.co/lofgwsos09'],
 ['@',
  'prismsperry',
  'like',
  'i',
  'work',
  'on',
  'myself',
  'so',
  'i',
  'can',
  'be',
  'better',
  'for',
  'me',
  'and',
  'you',
  '❤️'],
 ['@',
  'perrysmic',
  'not',
  'really',
  'but',
  'sometimes',
  'i',
  'do',
  "n't",
  'know',
  'my',
  'own',
  'strength',
  '😔'],
 ['@', 'focusonreid', 'great', 'get', 'your', 'pantone', 'book', 'out'],
 ['my',
  'fav',
  'combo',
  'of',
  'ppl',
  'all',
  'in',
  'one',
  'pic',
  ',',
  'i',
  'only',
  'roll',
  'with',
  'world',
  'changers❗️',
  'https',
  ':',
  '//t.co/oh37gaso7c'],
 ['halloween', '2k16', '🇺🇸💯🙏🏼', 'https', ':', '//t.co/vcwerxoeun'],
 ['thanks',
  '@',
  'covergirl',
  'for',
  'keeping',
  'everyone',
  'clean-cut',
  'and',
  'qt',
  'at',
  'hudson',
  'high',
  ',',
  'home',
  'of',
  'the',
  'poodles',
  '.',
  '💋',
  ',',
  '…',
  'https',
  ':',
  '//t.co/txo3ziptbl'],
 ['❤️bill',
  '&',
  'amp',
  ';',
  'hill',
  '4eva❤️',
  'hair',
  ',',
  'makeup',
  '&',
  'amp',
  ';',
  'prosthetics',
  'by',
  ':',
  '@',
  'tonyatalterian',
  'makeup_man…',
  'https',
  ':',
  '//t.co/ki4nl7ecmv'],
 ['having',
  'a',
  'little',
  'pre',
  'party',
  'before',
  'i',
  'take',
  'office',
  '#',
  'imwithme',
  'cheers',
  'to…',
  'https',
  ':',
  '//t.co/7szizrmwv0'],
 ['hbd', 'boss❗️🎂🎁🇺🇸', 'https', ':', '//t.co/0m4bkpnt82'],
 ['just',
  'went',
  'in',
  'the',
  'pit',
  '@',
  'kanyewest',
  'for',
  'my',
  'bday',
  '.',
  '32',
  'is',
  'lookin',
  '⬆️'],
 ['gave',
  'myself',
  'the',
  'best',
  'birthday',
  'present',
  'ever',
  'by',
  'voting',
  'today❗️wish',
  'hillaryclinton',
  'a',
  'happy',
  'birthday…',
  'https',
  ':',
  '//t.co/f53ik6tkg9'],
 ['help',
  'me',
  'celebrate',
  'my',
  'birthday',
  'with',
  'the',
  'purchase',
  'of',
  'a',
  'lifesaving',
  '@',
  'unicef',
  'inspired',
  'gift',
  '!',
  'https',
  ':',
  '//t.co/r2rsxs1rm7',
  '🎂',
  '#',
  'childrenfirst',
  '❤️'],
 ['@', 'wtfkates', 'yeah', 'but', '32', 'is', '23', 'backwards', 'so', '🍷'],
 ['@',
  'sella_sandra',
  'also',
  'this',
  'is',
  'real',
  'and',
  'not',
  'an',
  'edit',
  'i',
  'can',
  'tell',
  'by',
  'the',
  'icing',
  'i',
  "'m",
  'so',
  'proud',
  'of',
  'u'],
 ['@', 'greg_wells', 'go', 'to', 'bed', 'dad'],
 ['@', 'katycute_', 'nugget❗️'],
 ['@', 'caitsperry', 'combo'],
 ['@', 'katyperryforum', 'i', "'m", 'kanye'],
 ['aw',
  '.',
  'you',
  'made',
  'me',
  'cry',
  '.',
  'love',
  'you',
  'fam',
  '.',
  '❤️',
  'https',
  ':',
  '//t.co/ubitydazrs'],
 ['@', 'cynthialovely', 'you', "'re", 'clever'],
 ['dope', 's/o', '🙌🏼', 'https', ':', '//t.co/d4syo5oxqr'],
 ['level', '32', '.'],
 ['when',
  'you',
  'go',
  'dorm',
  'to',
  'dorm',
  'for',
  '@',
  'hillaryclinton',
  '@',
  'unlv',
  ':',
  'https',
  ':',
  '//t.co/qhpekuvtur'],
 ['tap',
  'it',
  'if',
  'you',
  "'re",
  'nasty',
  '@',
  'unlv',
  'campus',
  'https',
  ':',
  '//t.co/vdhh4kavlo'],
 ['@', 'radiantjareau', 'so', 'qt'],
 ['@', 'katycute_', 'this', 'edit', 'lol'],
 ['@', 'sella_sandra', 'my', 'birthdays', 'soon💅🏼'],
 ['@', 'kpcatt', '@', 'hillaryclinton', 'next', 'level'],
 ['@', 'perrysoldier', 'welcs', 'ho'],
 ['@', 'lillysgomez', '@', 'lucycowell14', 'not', 'for', 'long👋🏼'],
 ['@',
  'perrysoldier',
  'make',
  'fun',
  'of',
  'me',
  'now',
  ',',
  'thank',
  'me',
  'later',
  '💅🏼']]

In [60]:
# ['@', 'virginamerica', 'trying', 'to', 'add', 'my', 'boy', 'prince', 'to', 'my', 'ressie', '.', 'sf', 'this', 'thursday', '@', 'virginamerica', 'from', 'lax', 'http', ':', '//t.co/gsb2j3c4gm']
original_word_list = []
p_stemmed_list = []
s_stemmed_list = []
for each_list in words_in_each_string:
    print(each_list)
    for word in each_list:
        original_word_list.append(word)
        p_stemmed_list.append(p_stemmer.stem(word))
        s_stemmed_list.append(s_stemmer.stem(word))

['is', 'history', 'repeating', 'itself', '...', '?', '#', 'dontnormalizehate', 'https', ':', '//t.co/ngg11quhmk']
['@', 'barackobama', 'thank', 'you', 'for', 'your', 'incredible', 'grace', 'in', 'leadership', 'and', 'for', 'being', 'an', 'exceptional…', 'https', ':', '//t.co/zuqlzpt6df']
['life', 'goals', '.', 'https', ':', '//t.co/xin1qkmkql']
['me', 'right', 'now', '🙏🏻', 'https', ':', '//t.co/gw55c1wrwd']
['sisters', 'are', 'doin', "'", 'it', 'for', 'themselves', '!', '🙌🏻💪🏻❤️', 'https', ':', '//t.co/0shuuyubev']
['happy', '96th', 'gma', '#', 'fourmoreyears', '!', '🎈', '@', 'lacma', 'los', 'angeles', 'county', 'museum', 'of', 'art', 'https', ':', '//t.co/m9n7x8xdma']
['kyoto', ',', 'japan', '1', '.', '5', '.', '17.', 'https', ':', '//t.co/o28m0vw9lr']
['🇯🇵', '@', 'sanrio', 'puroland', 'https', ':', '//t.co/exvev5umbx']
['2017', 'resolution', ':', 'to', 'embody', 'authenticity', '!']
['sisters', '.', 'https', ':', '//t.co/5ze21x2ank']
['happy', 'holidays', '!', 'sending', 'love', 'and', 'light', 'to', 'every', 'corner', 'of', 'the', 'earth', '🎁']
['damn', ',', 'it', "'s", 'hard', 'to', 'wrap', 'presents', 'when', 'you', "'re", 'drunk', '.', 'cc', '@', 'santa']
['when', 'my', 'whole', 'fam', 'tryna', 'have', 'a', 'peaceful', 'holiday', '💁🏻hehehe', 'https', ':', '//t.co/feyq3hzdlz']
['when', 'your', 'holiday', 'shopping', 'is', 'woke', 'af', '❗️blklivesmatter', 'https', ':', '//t.co/srzzj7vhyc', 'https', ':', '//t.co/kwvyi8yi8l']
['@', 'shannonwoodward', 'have', 'you', 'been', 'hacked']
['this', 'week', 'santa', 'and', 'i', 'got', 'to', 'spread', 'some', 'cheer', 'and', 'have', 'a', 'carol', 'sing-a-long', 'with', 'some', 'beautiful…', 'https', ':', '//t.co/vl1bij4scz']
['love', 'the', 'music', 'therapy', 'program', 'at', 'chla', '!', 'https', ':', '//t.co/xptzrf3xxa']
['for', 'real', 'tho', 'https', ':', '//t.co/jxmv9q6wcs']
['i', 'ca', "n't", 'wait', 'to', 'recreate', 'this', 'on', 'a', 'tour', 'we', 'do', 'together', 'in', 'the', 'next', '10', 'years', 'pls', 'thnx', 'https', ':', '//t.co/pqz0ncunv6']
['i', 'wan', 'na', 'adopt', 'him', 'ilhsm', 'https', ':', '//t.co/5sr9whniey']
['@', 'jessesaintjohn', 'imma', 'make', 'a', 'best', 'of', '16', "'", 'spotify', 'playlist', 'and', 'half', 'of', 'these', 'are', 'on', 'there', '.', 'i', 'love', 'our', 'taste', '.']
['@', 'jessesaintjohn', '@', 'kanyewest', 'fade', 'doe']
['omg', 'deep', 'cut', ',', 'agreed', 'https', ':', '//t.co/0yglkuo3bj']
['same', 'https', ':', '//t.co/98vbup7bzi']
['fully', 'https', ':', '//t.co/iii4a58tpn']
['proof', 'that', 'your', 'voice', 'actually', 'matters', '!', '🙏🏼🙌🏼💪🏼😭', 'https', ':', '//t.co/tawl0a9y9e']
['this', 'holiday', 'season', 'be', 'the', 'girl', 'that', 'takes', 'jump', 'photos', 'at', 'the', 'mall', '☑️', 'wears', 'activewear', 'at', 'night…', 'https', ':', '//t.co/0egynkf5fk']
['slowly', ',', 'i', 'am', 'coming', 'down', 'from', 'the', 'beautiful', 'cloud', 'that', 'was', 'tuesday', 'night', "'s", 'unicef', 'snowflake…', 'https', ':', '//t.co/bia5wug56i']
['i', 'dare', 'you', 'to', 'find', 'a', 'better', 'live', 'vocal', 'performance', 'than', 'this', 'timeless', 'masterpiece', ':', 'https', ':', '//t.co/j1gw29kc7j', '#', 'jenniferholliday']
['this', '#', 'thanksgiving', '#', 'istandwithstandingrock', 'text', 'water', 'to', '82623', 'to', 'help', 'now', '!', 'sign', 'the', 'petition', 'here', ':', 'https', ':', '//t.co/gfhqkfsb0i']
['on', '#', 'thanksgiving', ',', 'a', 'day', 'with', 'complex', 'origins', ',', 'i', 'want', 'to', 'speak', 'up', 'in', 'support', 'of', 'the', 'standing', 'rock…', 'https', ':', '//t.co/ckyb7h3lcd']
['heading', 'into', 'my', 'family', '🦃-day', ',', 'i', "'m", 'mindful', 'about', 'building', 'a', 'bridge', 'thru', 'peaceful', 'convo', '.', 'try', 'this', 'guide', 'from', '@', 'nytimes', ':', 'https', ':', '//t.co/mzbbnw1zhd']
['great', 'tweet', '🏆', 'https', ':', '//t.co/z6qeywsbpt']
['.', '@', 'realdonaldtrump', 'how', 'bout', 'you', 'start', 'with', 'an', 'apology', 'for', 'your', 'divisive', ',', 'racist', ',', 'xenophobic', 'rhetoric', '?', '#', 'thanksgivingdayclapback']
['caught', 'a', 'big', 'one', 'this', 'week', '🎣', '...']
['let', 'it', 'be', 'known', '!', 'https', ':', '//t.co/axmajmnmgc']
['back', 'to', 'work', 'because', ':', 'all', 'of', 'the', 'above', '💪🏼', 'https', ':', '//t.co/duvh7jn8oi']
['operate', 'in', 'the', 'light', '.']
['confused', '?', 'overwhelmed', '?', 'here', "'s", 'the', 'brief', 'you', 'need', 'to', 'get', 'the', 'gist', ':', 'https', ':', '//t.co/4dwggerwmt']
['at', 'midnight', 'we', 'manifest', '✨🌚✨']
['yes', 'la', 'keep', 'leading', 'the', 'way', '❤️', 'https', ':', '//t.co/4lcjvcdj4u']
['it', "'s", 'time', 'to', 'turn', 'words', 'into', 'action❗️there', 'are', 'so', 'many', 'steps', 'to', 'take', ',', 'but', 'my', 'first', 'vow', 'is', 'to…', 'https', ':', '//t.co/1dwetgxbed']
['thank', 'you', 'to', 'the', 'men', 'and', 'women', 'protecting', 'freedom', ',', 'liberty', ',', 'and', 'equality', 'for', 'all', '.', '🙏🏼🇺🇸', 'https', ':', '//t.co/0lcb7vydrx']
['from', 'pastor', 'john', 'pavlovitz', '``', 'this', 'is', 'not', 'about', 'losing', 'an', 'election', "''", 'https', ':', '//t.co/vvxyzvkyyi']
['lets', 'also', 'work', 'on', 'the', 'hearts', 'and', 'minds', 'of', 'this', 'country', 'and', 'that', 'is', 'how', 'real', 'change', 'will', 'begin', '.']
['remember', 'to', 'take', 'care', 'of', 'your', 'mental', 'health', '.', 'talk', 'with', 'counselors/therapists/ur', 'tribe', '.', 'lean', 'on', 'your', 'friends', ',', 'do', "n't", 'stop', 'communicating', '.']
['we', 'need', 'more', 'courageous', 'men', 'like', 'this', 'to', 'speak', 'up', 'and', 'say', 'that', 'there', 'is', 'great', 'examples', 'of', 'men', 'out', 'there', ':', 'https', ':', '//t.co/daruhfyssm']
['🙏🏼🇺🇸peacefully', 'protest🇺🇸🙏🏼']
['fight', 'for', 'what', 'is', 'right', '.']
['do', 'not', 'sit', 'still', '.', 'do', 'not', 'weep', '.', 'move', '.', 'we', 'are', 'not', 'a', 'nation', 'that', 'will', 'let', 'hate', 'lead', 'us', '.']
['we', 'will', 'never', 'be', 'silenced', '.', '#', 'lovetrumpshate']
['power', 'to', 'the', 'people']
['rise', 'up']
['the', 'revolution', 'is', 'coming', '.']
['we', 'will', 'never', 'be', 'silenced', '.', 'https', ':', '//t.co/co4cybxg8j']
['gon', 'na', 'cry', 'my', 'false', 'eye', 'lashes', 'off', 'tonight', '.', '❤️🙏🏼🇺🇸']
['throw', 'back', 'to', 'oct', '25th', 'when', 'i', 'gave', 'myself', 'the', 'best', 'bday', 'prezzy', 'ever', 'by', 'voting', 'for', 'my', 'girl…', 'https', ':', '//t.co/i68tg6ixi1']
['hope', 'you', 'are', 'roaring', 'your', 'way', 'to', 'the', 'polls', 'still', '!', '👊🏼🦁🐯❤️🇺🇸', ':', 'https', ':', '//t.co/tnqit6zia6']
['✔️ote', '#', 'yeson64', '!', 'let', "'s", 'rewrite', 'our', 'narrative', 'california❗️', 'https', ':', '//t.co/mys49evfef', 'by', '@', 'dreamhampton']
['🔮', 'https', ':', '//t.co/afzxsirfhn']
['if', 'hell', 'had', 'a', 'smell', 'it', 'would', 'be', 'used', 'dental', 'floss', 'and', 'earring', 'backs', '.', '😷']
['my', 'name', 'is', '🐶', 'nugget', '🐶', 'and', 'i', 'approve', 'this', 'message', '.', 'go', '✔ote❗find', 'out', 'where', ':', 'https', ':', '//t.co/rl2nzq97cd', 'https', ':', '//t.co/qgouyddqac']
['want', 'niche', '?', 'inside', 'jokes', '?', 'mega', 'meta', '?', 'think', 'ur', 'the', 'only', '1', 'thinking', 'the', 'demented', 'way', 'ur', 'thinking', '?', 'go', 'see', '``', 'oh', 'hello', "''", 'on', 'broadway', '&', 'amp', ';', 'find', 'ur', 'ppl', '.']
['hill-adelphia', 'ftw', '!', 'in', 'less', 'than', '3', 'days', 'be', 'apart', 'of', 'history', 'and', 'make', '#', 'herstory', '🇺🇸', '#', 'november8th…', 'https', ':', '//t.co/pnv46unbxj']
['omg', 'idk', 'this', 'is', 'totes', 'my', 'vocab', 'https', ':', '//t.co/weyhipxb4q']
['done', 'with', 'my', '🎄christmas🎄shopping', '✔️', 'https', ':', '//t.co/ww8n4sirxx']
['🎣🐟🐠🐋']
['aye', '!', '📲', 'text', 'roar', 'to', '47246', 'to', 'score', 'free', '🎟', 'to', 'see', 'me', '&', 'amp', ';', '@', 'hillaryclinton', 'this', 'saturday', 'in', 'philly', '!', '(', 'i', "'ll", 'be', 'the', 'one', 'singing', '🎤', ')', '#', 'lovetrumpshate❤️']
['welp', '.', 'the', 'airline', 'lost', 'my', 'luggage', 'so', 'i', 'guess', 'i', "'ll", 'just', 'wear', 'my', 'tracksuit', 'for', 'halloween', '💁🏻', 'now', 'that', "'s", 'scary', '.', '🎃']
['🎃my', 'fam', '&', 'gt', ';', 'your', 'fam🎃', 'i', 'have', 'roots', 'from', 'both', 'santa', 'barbara', 'and', 'arkansas', '(', 'think', 'appalachian…', 'https', ':', '//t.co/lofgwsos09']
['@', 'prismsperry', 'like', 'i', 'work', 'on', 'myself', 'so', 'i', 'can', 'be', 'better', 'for', 'me', 'and', 'you', '❤️']
['@', 'perrysmic', 'not', 'really', 'but', 'sometimes', 'i', 'do', "n't", 'know', 'my', 'own', 'strength', '😔']
['@', 'focusonreid', 'great', 'get', 'your', 'pantone', 'book', 'out']
['my', 'fav', 'combo', 'of', 'ppl', 'all', 'in', 'one', 'pic', ',', 'i', 'only', 'roll', 'with', 'world', 'changers❗️', 'https', ':', '//t.co/oh37gaso7c']
['halloween', '2k16', '🇺🇸💯🙏🏼', 'https', ':', '//t.co/vcwerxoeun']
['thanks', '@', 'covergirl', 'for', 'keeping', 'everyone', 'clean-cut', 'and', 'qt', 'at', 'hudson', 'high', ',', 'home', 'of', 'the', 'poodles', '.', '💋', ',', '…', 'https', ':', '//t.co/txo3ziptbl']
['❤️bill', '&', 'amp', ';', 'hill', '4eva❤️', 'hair', ',', 'makeup', '&', 'amp', ';', 'prosthetics', 'by', ':', '@', 'tonyatalterian', 'makeup_man…', 'https', ':', '//t.co/ki4nl7ecmv']
['having', 'a', 'little', 'pre', 'party', 'before', 'i', 'take', 'office', '#', 'imwithme', 'cheers', 'to…', 'https', ':', '//t.co/7szizrmwv0']
['hbd', 'boss❗️🎂🎁🇺🇸', 'https', ':', '//t.co/0m4bkpnt82']
['just', 'went', 'in', 'the', 'pit', '@', 'kanyewest', 'for', 'my', 'bday', '.', '32', 'is', 'lookin', '⬆️']
['gave', 'myself', 'the', 'best', 'birthday', 'present', 'ever', 'by', 'voting', 'today❗️wish', 'hillaryclinton', 'a', 'happy', 'birthday…', 'https', ':', '//t.co/f53ik6tkg9']
['help', 'me', 'celebrate', 'my', 'birthday', 'with', 'the', 'purchase', 'of', 'a', 'lifesaving', '@', 'unicef', 'inspired', 'gift', '!', 'https', ':', '//t.co/r2rsxs1rm7', '🎂', '#', 'childrenfirst', '❤️']
['@', 'wtfkates', 'yeah', 'but', '32', 'is', '23', 'backwards', 'so', '🍷']
['@', 'sella_sandra', 'also', 'this', 'is', 'real', 'and', 'not', 'an', 'edit', 'i', 'can', 'tell', 'by', 'the', 'icing', 'i', "'m", 'so', 'proud', 'of', 'u']
['@', 'greg_wells', 'go', 'to', 'bed', 'dad']
['@', 'katycute_', 'nugget❗️']
['@', 'caitsperry', 'combo']
['@', 'katyperryforum', 'i', "'m", 'kanye']
['aw', '.', 'you', 'made', 'me', 'cry', '.', 'love', 'you', 'fam', '.', '❤️', 'https', ':', '//t.co/ubitydazrs']
['@', 'cynthialovely', 'you', "'re", 'clever']
['dope', 's/o', '🙌🏼', 'https', ':', '//t.co/d4syo5oxqr']
['level', '32', '.']
['when', 'you', 'go', 'dorm', 'to', 'dorm', 'for', '@', 'hillaryclinton', '@', 'unlv', ':', 'https', ':', '//t.co/qhpekuvtur']
['tap', 'it', 'if', 'you', "'re", 'nasty', '@', 'unlv', 'campus', 'https', ':', '//t.co/vdhh4kavlo']
['@', 'radiantjareau', 'so', 'qt']
['@', 'katycute_', 'this', 'edit', 'lol']
['@', 'sella_sandra', 'my', 'birthdays', 'soon💅🏼']
['@', 'kpcatt', '@', 'hillaryclinton', 'next', 'level']
['@', 'perrysoldier', 'welcs', 'ho']
['@', 'lillysgomez', '@', 'lucycowell14', 'not', 'for', 'long👋🏼']
['@', 'perrysoldier', 'make', 'fun', 'of', 'me', 'now', ',', 'thank', 'me', 'later', '💅🏼']

In [61]:
data =pd.DataFrame(original_word_list, columns=['Original word'])
data['Porter Stemmed'] = p_stemmed_list
data['Snowball Stemmed'] = s_stemmed_list
data[:-50]

     Original word Porter Stemmed Snowball Stemmed
0               is             is               is
1          history        histori          histori
2        repeating         repeat           repeat
3           itself         itself           itself
4              ...            ...              ...
...            ...            ...              ...
1253           tap            tap              tap
1254            it             it               it
1255            if             if               if
1256           you            you              you
1257           're            're               re

[1258 rows x 3 columns]

In [63]:
#Let's see on which words the stemmers give different results!
data.loc[data['Porter Stemmed'] != data['Snowball Stemmed']]

# You can observe that Snowball_Stemming is more accurate.
# Also, observe that the root of some of the words is an incomplete English word.

     Original word Porter Stemmed Snowball Stemmed
8            https           http            https
26           https           http            https
32           https           http            https
39           https           http            https
51           https           http            https
...            ...            ...              ...
1250         https           http            https
1257           're            're               re
1261        campus          campu           campus
1262         https           http            https
1271          this            thi             this

[87 rows x 3 columns]

Lemmatization
Stemming is a process that stems or removes last few characters from a word, often leading to incorrect meanings and spelling. Lemmatization considers the context and converts the word to its meaningful base form, which is called Lemma.

For instance, stemming the word 'amazed' would return 'amaz'. However, lemmatizing the word 'amazed' would give 'amaze'.

In [64]:
print(p_stemmer.stem('amazed'))
print(s_stemmer.stem('amazed'))

amaz
amaz

In [65]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('amazed')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

'amazed'

In [68]:
lemmatizer.lemmatize('amazed', pos='v' )
# Lemmatization needs the Parts of Speech to generate the correct lemma. The default pos is 'n' (Noun).
# 'v' stands for verb.

'amaze'

:# Tagging Parts of Speech (PoS)

In [71]:
import nltk
text = df.loc[5,'content']
print(text)

tokens_list = nltk.word_tokenize(text)
tokens_list

happy 96th gma #fourmoreyears! 🎈 @ LACMA Los Angeles County Museum of Art https://t.co/M9n7X8xdmA

['happy',
 '96th',
 'gma',
 '#',
 'fourmoreyears',
 '!',
 '🎈',
 '@',
 'LACMA',
 'Los',
 'Angeles',
 'County',
 'Museum',
 'of',
 'Art',
 'https',
 ':',
 '//t.co/M9n7X8xdmA']

In [79]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')
tokens_after_SW = []
for word in tokens_list:
        if word not in sw_list:
            tokens_after_SW.append(word)

tagged_tokens = nltk.pos_tag(tokens_after_SW) #Tagging each word with PoS
tagged_tokens

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

[('happy', 'JJ'),
 ('96th', 'CD'),
 ('gma', 'NN'),
 ('#', '#'),
 ('fourmoreyears', 'NNS'),
 ('🎈', 'VBP'),
 ('LACMA', 'NNP'),
 ('Los', 'NNP'),
 ('Angeles', 'NNP'),
 ('County', 'NNP'),
 ('Museum', 'NNP'),
 ('Art', 'NNP'),
 ('https', 'NN'),
 (':', ':'),
 ('//t.co/M9n7X8xdmA', 'NN')]

In [82]:
import nltk

nltk.download('tagsets_json')

#Refer to the complete list of tags here!
nltk.help.upenn_tagset()

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or conjunction, subordinating
    astride among uppon whether out inside pro despite on by throughout
    below within for towards near behind atop around if like until below
    next into if beside ...
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
JJR: adjective, comparative
    bleaker braver breezier briefer brighter brisker broader bumper busier
    calmer cheaper choosier cleaner clearer closer colder commoner costlier
    cozier creamier crunchier cuter ...
JJS: adjective, superlative
    calmest cheapest choicest classiest cleanest clearest closest commonest
    corniest costliest crassest creepiest crudest cutest darkest deadliest
    dearest deepest densest dinkiest ...
LS: list item marker
    A A. B B. C C. D E F First G H I J K One SP-44001 SP-44002 SP-44005
    SP-44007 Second Third Three Two * a b c d first five four one six three
    two
MD: modal auxiliary
    can cannot could couldn't dare may might must need ought shall should
    shouldn't will would
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
NNP: noun, proper, singular
    Motown Venneboerger Czestochwa Ranzer Conchita Trumplane Christos
    Oceanside Escobar Kreisler Sawyer Cougar Yvette Ervin ODI Darryl CTCA
    Shannon A.K.C. Meltex Liverpool ...
NNPS: noun, proper, plural
    Americans Americas Amharas Amityvilles Amusements Anarcho-Syndicalists
    Andalusians Andes Andruses Angels Animals Anthony Antilles Antiques
    Apache Apaches Apocrypha ...
NNS: noun, common, plural
    undergraduates scotches bric-a-brac products bodyguards facets coasts
    divestitures storehouses designs clubs fragrances averages
    subjectivists apprehensions muses factory-jobs ...
PDT: pre-determiner
    all both half many quite such sure this
POS: genitive marker
    ' 's
PRP: pronoun, personal
    hers herself him himself hisself it itself me myself one oneself ours
    ourselves ownself self she thee theirs them themselves they thou thy us
PRP$: pronoun, possessive
    her his mine my our ours their thy your
RB: adverb
    occasionally unabatingly maddeningly adventurously professedly
    stirringly prominently technologically magisterially predominately
    swiftly fiscally pitilessly ...
RBR: adverb, comparative
    further gloomier grander graver greater grimmer harder harsher
    healthier heavier higher however larger later leaner lengthier less-
    perfectly lesser lonelier longer louder lower more ...
RBS: adverb, superlative
    best biggest bluntest earliest farthest first furthest hardest
    heartiest highest largest least less most nearest second tightest worst
RP: particle
    aboard about across along apart around aside at away back before behind
    by crop down ever fast for forth from go high i.e. in into just later
    low more off on open out over per pie raising start teeth that through
    under unto up up-pp upon whole with you
SYM: symbol
    % & ' '' ''. ) ). * + ,. < = > @ A[fj] U.S U.S.S.R * ** ***
TO: "to" as preposition or infinitive marker
    to
UH: interjection
    Goodbye Goody Gosh Wow Jeepers Jee-sus Hubba Hey Kee-reist Oops amen
    huh howdy uh dammit whammo shucks heck anyways whodunnit honey golly
    man baby diddle hush sonuvabitch ...
VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...
VBD: verb, past tense
    dipped pleaded swiped regummed soaked tidied convened halted registered
    cushioned exacted snubbed strode aimed adopted belied figgered
    speculated wore appreciated contemplated ...
VBG: verb, present participle or gerund
    telegraphing stirring focusing angering judging stalling lactating
    hankerin' alleging veering capping approaching traveling besieging
    encrypting interrupting erasing wincing ...
VBN: verb, past participle
    multihulled dilapidated aerosolized chaired languished panelized used
    experimented flourished imitated reunifed factored condensed sheared
    unsettled primed dubbed desired ...
VBP: verb, present tense, not 3rd person singular
    predominate wrap resort sue twist spill cure lengthen brush terminate
    appear tend stray glisten obtain comprise detest tease attract
    emphasize mold postpone sever return wag ...
VBZ: verb, present tense, 3rd person singular
    bases reconstructs marks mixes displeases seals carps weaves snatches
    slumps stretches authorizes smolders pictures emerges stockpiles
    seduces fizzes uses bolsters slaps speaks pleads ...
WDT: WH-determiner
    that what whatever which whichever
WP: WH-pronoun
    that what whatever whatsoever which who whom whosoever
WP$: WH-pronoun, possessive
    whose
WRB: Wh-adverb
    how however whence whenever where whereby whereever wherein whereof why
``: opening quotation mark
    ` ``

[nltk_data] Downloading package tagsets_json to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Unzipping help/tagsets_json.zip.

##FYI, NLTK has another Tagger: WordNet Tagger. You can explore it in your free time.

In [83]:
# Define a function to get the POS tag for lemmatization
def get_pos(tag):
    if tag.startswith('J'):
        return 'a' #Adjective
    elif tag.startswith('V'):
        return 'v' #Verb
    elif tag.startswith('N'):
        return 'n' #Noun
    elif tag.startswith('R'):
        return 'r' #Adverb
    else:
        return 'n'

In [84]:
#Lemmatization on a sample string. Stopwords have been removed.
for token, tag in tagged_tokens:
    print("Word:",token,"\nLemmatized Word:",lemmatizer.lemmatize(token.lower(),pos = get_pos(tag)))
    print('***********************')

Word: happy
Lemmatized Word: happy
***********************
Word: 96th
Lemmatized Word: 96th
***********************
Word: gma
Lemmatized Word: gma
***********************
Word: #
Lemmatized Word: #
***********************
Word: fourmoreyears
Lemmatized Word: fourmoreyears
***********************
Word: 🎈
Lemmatized Word: 🎈
***********************
Word: LACMA
Lemmatized Word: lacma
***********************
Word: Los
Lemmatized Word: los
***********************
Word: Angeles
Lemmatized Word: angeles
***********************
Word: County
Lemmatized Word: county
***********************
Word: Museum
Lemmatized Word: museum
***********************
Word: Art
Lemmatized Word: art
***********************
Word: https
Lemmatized Word: http
***********************
Word: :
Lemmatized Word: :
***********************
Word: //t.co/M9n7X8xdmA
Lemmatized Word: //t.co/m9n7x8xdma
***********************